sudo: required
dist: trusty
language: cpp
compiler: gcc
notifications:
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - xorg-dev
    - libgtk-3-dev
    - libglu1-mesa-dev

install: true
script:
  - mkdir external/glfw/include/GL
  - wget --no-check-certificate -P /src/thirdparty/gl3w/include/GL http://www.opengl.org/registry/api/GL/glcorearb.h
  - mkdir build && cd build && cmake ../ && make -r -j 2