sudo: required
dist: trusty
language: cpp
compiler: gcc
notifications:
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - gcc-5
    - g++-5
    - cmake
    - xorg-dev
    - libgtk-3-dev
    - libglu1-mesa-dev
    - nvidia-profiler
    - nvidia-cuda-dev
    - nvidia-cuda-toolkit
    - clang-4.0
    - clang-tidy-4.0

install: true
jobs:
  include:
  - stage: build
    name: Build test
    script:
    - mkdir build && cd build && cmake ../ && make -r -j 2
    - "../sandbox/bin/Release/neptun -test"
  - script:
    - mkdir build && cd build && cmake ../ && make clang-tidy
    - cat clang_tidy_report.txt
    name: Clang Tidy
