sudo: required
dist: trusty
language: cpp
compiler: gcc
notifications:
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - xorg-dev
    - libgtk-3-dev
    - libglu1-mesa-dev
    - nvidia-profiler
    - nvidia-cuda-dev
    - nvidia-cuda-toolkit
install: true
script:
  - curl -L "https://github.com/aytekaman/neptun-deps/releases/download/v0.1/neptun-linux-deps.tgz" > deps.tgz
  - mkdir build && cd build && cmake ../ && make -r -j 2
  - ../sandbox/bin/Release/neptun -test
  